export const workCasesData = [
  {
    company: "BOL.COM",
    urlTo: "#",
    type: "card",
    category: "experience",
    industry: "ecommerce",
    description: "A Summer island in the Netherlands",
    img: "11c921da-e495-4ee1-b325-014556612772",
  },
  {
    company: "KEMPEN",
    urlTo: "#",
    type: "card",
    category: "growth",
    industry: "banking",
    description: "Not some average banking website",
    img: "4d13fbac-b4f7-493e-b0d7-6054a7e86951",
  },
  {
    company: "PHILIPS",
    urlTo: "#",
    type: "card",
    category: "creative",
    industry: "electronics",
    description: "Beautiful design meets innovative technology",
    img: "31f7e4cf-b7fc-429c-8bbd-6f785279f6aa",
  },
  {
    company: "GEMEENTEMUSEUM",
    urlTo: "#",
    type: "card",
    category: "engineering",
    industry: "culture",
    description: "A 100 years of Mondriaan & De Stijl",
    img: "ba7413bc-14a6-43c0-bf77-b1f9ae0d12ce",
  },
  {
    type: "note",
    category: "engineering",
    industry: "ecommerce",
    mainCard: {
      urlTo: "#",
      category: "engineering",
      industry: "ecommerce",
      company: "FLORENSIS",
      description: "Rethinking the entire online ecosystem",
      img: "571f24d7-12a6-4021-bfa5-714a2d83de77",
    },
    textCards: [
      {
        company: "MICROSOFT",
        urlTo: "#",
        type: "inlineCard",
        category: "growth",
        industry: "electronics",
        description:
          "Tapping into Ireland’s unique gaming culture and bringing a fresh flavour to their Xbox social media channels",
      },
      {
        company: "O’NEILL",
        urlTo: "#",
        type: "inlineCard",
        category: "experience",
        industry: "fashion",
        description:
          "Integrating existing content into O’Neills’s new e-commerce platform",
      },
      {
        company: "MICROSOFT",
        urlTo: "#",
        type: "inlineCard",
        category: "growth",
        industry: "electronics",
        description:
          "Tapping into Ireland’s unique gaming culture and bringing a fresh flavour to their Xbox social media channels",
      },
    ],
  },
  {
    company: "BE LIGHTNING",
    urlTo: "#",
    type: "card",
    category: "growth",
    industry: "ecommerce",
    description: "Delivering clarity on a global scale",
    img: "9947cb53-30c7-4555-97a2-e8a28c6e438d",
  },
  {
    company: "TUI",
    urlTo: "#",
    type: "card",
    category: "creative",
    industry: "tourism",
    description: "Swipe to find your next holiday destination",
    img: "8369a09f-0ff0-440a-8c07-b7d3837d53e7",
  },
  {
    type: "note",
    category: "engineering",
    industry: "ecommerce",
    isReversed: true,
    mainCard: {
      category: "engineering",
      industry: "ecommerce",
      type: "card",
      company: "FLORENSIS",
      urlTo: "#",
      description: "Rethinking the entire online ecosystem",
      img: "fcaaca6f-aa98-4a0a-b90e-f8c928a65528",
    },
    textCards: [
      {
        company: "MICROSOFT",
        urlTo: "#",
        type: "inlineCard",
        category: "growth",
        industry: "electronics",
        description:
          "Tapping into Ireland’s unique gaming culture and bringing a fresh flavour to their Xbox social media channels",
      },
      {
        company: "O’NEILL",
        urlTo: "#",
        type: "inlineCard",
        category: "experience",
        industry: "fashion",
        description:
          "Integrating existing content into O’Neills’s new e-commerce platform",
      },
      {
        company: "MICROSOFT",
        urlTo: "#",
        type: "inlineCard",
        category: "growth",
        industry: "electronics",
        description:
          "Tapping into Ireland’s unique gaming culture and bringing a fresh flavour to their Xbox social media channels",
      },
    ],
  },
  {
    company: "CHOCOMEL",
    urlTo: "#",
    type: "card",
    category: "creative",
    industry: "food",
    description: "A campaign for the limited edition letter packs",
    img: "aa87102d-b240-43e0-9184-ded67ca5473f",
  },
  {
    company: "JBL",
    urlTo: "#",
    type: "card",
    category: "experience",
    industry: "electronics",
    description: "Live like a champion with Jerome Boateng",
    img: "8c9b40ef-17e0-4fdc-a760-9e8f3f13c57a",
  },
  {
    company: "ZALANDO",
    urlTo: "#",
    type: "card",
    category: "growth",
    industry: "fashion",
    description: "Innovative SEO and content strategy for Zalando",
    img: "8de7e602-f4ea-4f12-9c12-b04eb1ff703f",
  },
  {
    company: "KONINKLIJKE BIBLIOTHEEK",
    urlTo: "#",
    type: "card",
    category: "creative",
    industry: "culture",
    description: "The search of the most influential book ever",
    img: "33858677-9068-4b61-a6c9-5dbb744b7eb6",
  },
  {
    author: "MATTIJS TEN DRINK - CEO, TRANSAVIA",
    urlTo: "#",
    type: "quote",
    category: "growth",
    quote:
      "“Dept helped us tell our story through a bold new identity and a robust online experience. To the tone of 60% growth in online bookings in just one month””",
  },
  {
    company: "LIBERTY GLOBAL",
    urlTo: "#",
    type: "card",
    category: "engineering",
    industry: "ecommerce",
    description: "Delivering complex commerce solutions",
    img: "4d3c1c93-16e9-48f0-8359-d59281351e2d",
  },
  {
    company: "ARLA",
    urlTo: "#",
    type: "card",
    category: "creative",
    industry: "food",
    description: "Swipe to find your next holiday destination",
    img: "eb4bfb16-dda0-40c3-9053-0ee50b41839d",
  },
];
